blank_issues_enabled: true
# contact_links:
#   - name: 💬 Discussions
#     url: https://github.com/Lunarwing-Games/lunar/discussions
#     about: For typical discussion on Lunar, questions and feedback go here.
